version: "3.8"

services:
  be:
    image: hyeu420/ecommerce-be:latest
    container_name: be
    ports:
      - "8080:8080"
    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - my-app
    restart: unless-stopped

  fe:
    image: hyeu420/ecommerce-fe:latest
    container_name: fe
    ports:
      - "80:80"
    networks:
      - my-app
    depends_on:
      - be
    restart: unless-stopped

networks:
  my-app:
    driver: bridge
