version: "3.8"

services:
  db:
    build: ./db
    image: hyeu420/ecommerce-db:latest
    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-app
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  be:
    build: ./be
    image: hyeu420/ecommerce-be:latest
    container_name: be
    ports:
      - "8080:8080"
    networks:
      - my-app
    depends_on:
      db:
        condition: service_healthy
  fe:
    build: ./fe
    image: hyeu420/ecommerce-fe:latest
    container_name: fe
    ports:
      - "80:80"
    networks:
      - my-app
    depends_on:
      - be
volumes:
  db_data:
networks:
  my-app:
    driver: bridge
