# Server
server.port=8080

# MySQL Database
spring.datasource.url=${DB_URL:jdbc:mysql://db:3306/ecommerce_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=secrets_key
jwt.expiration=86400000

# Init data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
